# RAG Chat Application Configuration v2.0
# Complete configuration with all enhanced features

# ============================================
# CORE PATHS
# ============================================
data_path: ./data                    # Directory containing documents to index
vector_db_path: ./vector_db          # ChromaDB storage location
vector_backup_path: ./vector_db_backup  # Backup location for vectorstore
snapshot_path: ./snapshots           # Session snapshots directory
prompt_path: ./prompts.yaml          # Custom prompts file
log_path: ./logs                     # Log files directory

# ============================================
# LOGGING CONFIGURATION
# ============================================
logging:
  level: INFO                        # File log level: DEBUG, INFO, WARNING, ERROR
  console_level: INFO                # Console log level (can be different)
  file_path: ./logs/rag_chat.log     # Main log file location
  max_size_mb: 100                   # Max log file size before rotation
  backup_count: 5                    # Number of backup log files to keep

# ============================================
# SECURITY CONFIGURATION
# ============================================
security:
  allowed_file_types: [".pdf", ".txt", ".json", ".html"]
  max_file_size_mb: 100
  allowed_directories: ["./data"]
  enable_content_scanning: true

# ============================================
# PERFORMANCE CONFIGURATION
# ============================================
performance:
  batch_size: 100
  max_concurrent_operations: 4
  enable_async: true
  cache_enabled: true
  cache_size_mb: 500

# ============================================
# DOCUMENT PROCESSING
# ============================================
chunk:
  size: 800
  overlap: 80

# ============================================
# EMBEDDING CONFIGURATION
# ============================================
embedding:
  model_name: "all-MiniLM-L6-v2"

# ============================================
# RETRIEVAL CONFIGURATION
# ============================================
retrieval:
  search_type: "hybrid"              # Options: semantic, keyword, hybrid
  top_k: 5
  semantic_weight: 0.7
  keyword_weight: 0.3
  rerank: true
  diversity_threshold: 0.7

# ============================================
# LLM CONFIGURATION
# ============================================
# Single model configuration (backward compatibility)
llm:
  local_model_path: ./models/mistral-7b-instruct-v0.1.Q4_K_M.gguf
  temperature: 0.3
  top_p: 0.9
  max_tokens: 400
  n_ctx: 2048
  n_threads: 6
  n_gpu_layers: -1                   # -1 for auto, 0 for CPU only

# Multi-model configuration
models:
  default_profile: "balanced"
  
  profiles:
    fast:
      provider: "local"
      model: "mistral-7b"
      max_tokens: 256
      temperature: 0.3
      context_window: 2048
      custom_params:
        model_path: "./models/mistral-7b-instruct-v0.1.Q4_K_M.gguf"
        n_ctx: 2048
        n_threads: 6
    
    balanced:
      provider: "local"
      model: "mistral-7b"
      max_tokens: 512
      temperature: 0.5
      context_window: 4096
      custom_params:
        model_path: "./models/mistral-7b-instruct-v0.1.Q4_K_M.gguf"
        n_ctx: 4096
        n_threads: 8
    
    # Uncomment and configure for API models
    # quality:
    #   provider: "openai"
    #   model: "gpt-4"
    #   max_tokens: 1024
    #   temperature: 0.7
    #   context_window: 8192
    #   cost_per_1k_tokens: 0.03
  
  fallback_chain: ["balanced", "fast"]

# ============================================
# MEMORY CONFIGURATION
# ============================================
memory:
  max_turns_before_summary: 20
  summary_token_limit: 500
  enable_compression: true
  auto_cleanup_days: 30

# ============================================
# MONITORING CONFIGURATION
# ============================================
monitoring:
  enabled: true
  retention_hours: 24
  persist_path: "./metrics/metrics.json"

# ============================================
# WEB SETTINGS
# ============================================
web:
  timeout: 10
  max_retries: 3